### ISSUE TITLE
Some BtreeList methods should be declared as const member methods

### ISSUE THREAD

**Issue by NachtRaveVL** [davetcc/SimpleCollections#7]
BtreeList's various access methods that do not modify underlying data, such as getByKey, itemAtIndex, capacity, etc., should be declared as const member methods. This allows it to be used in the case where the returned object is a const list, e.g. when you want to save the cost of a list copy constructor so you return your own private list by reference but declared as const to avoid outside modification. In such a case, you should still be able to look up items, get the capacity, etc., without violating C++ qualifiers.

**Comment by davetcc** [comment]
Agreed, as per the other comment on #8 I'll take a look after tcMenu 2.3.2

**Comment by davetcc** [comment]
I've done this and committed it to main. I'll release it once it has gone through quite a bit of testing. It would be good if you could try the code from there.
